# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 353843c8a6f572d6e6a5c88fd3cc87ed3dd263084520bd6b61e39e8512103d15d774f15bb9d4afc302ed4aba2f1a6154efb20f759114cb24f5a5f6ff07795dcb

test:
  secret_key_base: 01692996d004847875fb55b18591470fa5cfa8e6b5c5586d2baa373b6f6129faadf5c4b177cf79f4852dfb30bda7e395de197f226d901caa45ae868bea72266c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
